resources:
  - ../base

labels:
  - pairs:
      pool: opencode-golang

namePrefix: opencode-golang-

images:
  - name: agent-opencode
    newName: agent-opencode-golang
    newTag: latest

patches:
  - path: warmpool-template.yaml
    target:
      group: extensions.agents.x-k8s.io
      version: v1alpha1
      kind: SandboxWarmPool
      name: sandbox-warmpool
